version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ARTEMIS_PORT=:8080
      - REDIS_URI=redis:6379
      - REDIS_PWD=artemis
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=artemis
      - POSTGRES_PWD=artemis
      - POSTGRES_DB=db_artemis
    networks:
      - artemis
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6.0.15-alpine
    restart: always
    command: redis-server --requirepass artemis
    ports:
      - "6379:6379"
    networks:
      - artemis

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=artemis
      - POSTGRES_USER=artemis
      - POSTGRES_DB=db_artemis
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    networks:
      - artemis

networks:
  artemis:
    driver: bridge